language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py32
  - TOXENV=py33
  # - TOXENV=py34  # Travis-CI does not support 3.4 yet
install:
  - travis_retry pip install tox==1.6.1
script:
  - travis_retry tox
