language: python
sudo: false
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
install:
  # "virtualenv<14.0.0" is needed for Python 3.2 compat
  - travis_retry pip install "virtualenv<14.0.0" "tox==1.6.1"
script:
  - travis_retry tox
