language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
install:
  # "virtualenv<14.0.0" is needed for Python 3.2 compat
  - travis_retry pip install "virtualenv<14.0.0" tox
script:
  - travis_retry tox
